name: Publish Release

on:
    workflow_dispatch:
      inputs:
        target-branch:
          description: 'Branch to target'
          required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3
       with:
        ref: ${{ github.event.inputs.target-branch }}
        # token: ${{ secrets.TAG_TOKEN }}

   
     - name: Current branch
       run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo $branch
